name: "arrs"

x-lockdown: &lockdown
  # prevents write access to the image itself
  read_only: true
  # prevents any process within the container to gain more privileges
  security_opt:
    - "no-new-privileges=true"

services:
  sabnzbd:
    image: "11notes/sabnzbd:4.5.4"
    <<: *lockdown
    environment:
      TZ: "Europe/Zurich"
    volumes:
      - "sabnzbd.etc:/sabnzbd/etc"
    tmpfs:
      # required for read-only image
      - "/tmp:uid=1000,gid=1000"
    ports:
      - "3000:8080/tcp"
    networks:
      frontend:
    restart: "always"

volumes:
  sabnzbd.etc:

networks:
  frontend: